index.js

I think instead of 
```js
queryId.$query._id = id;
```
should be
```js
query.$query._id = id;
```

Fix typo in queryPollDoc

---

.travis.yml
README.md
index.js
package.json
test/mocha.opts
test/test.js

* Use `makeSortedQuery` from sharedb-mingo-memory in tests
* Deprecate the `{$query: ..., $count: ...}` style queries that no longer work in Mongo 3.2. The new query format is `{foo: bar, $count: ...}`. Properties that begin with $ are mapped to collection or cursor methods, where the value of the property maps to the argument to the method. (The exception is `$readPref` which maps an object into the two arguments passed into the `readPref` cursor method)
* Expand support to all collection and cursor operators supported by Mongo 3.2 and Node driver 2.1
* Replace normalizeQuery with parseQuery
* Backwards incompatible changes:
* `{$mapReduce: true, $map: ..., $reduce: ..., $scope: ...}` is now `{$mapReduce: {map: ..., reduce: ..., scope: ...}}`
* `{$distinct: true: $field: 'y'}` is now …

Deprecate $query, use cursor methods instead of dollar properties in queries

---

README.md
index.js
package.json
test/test.js

Increase test coverage to 95%

---

index.js
test/test.js

Instead, pass a callback into the 'mongo' property

Deprecate ShareDb({mongo: (mongo connection})

---

index.js

Implements feature requested in issue #42 and now tested via tests in ShareDB

implement {metadata: true} for methods that get snapshots or ops

---

README.md

The link to the node-mongodb-native package was broken, because its URL was interrupted with a newline in the Markdown.

Fix broken mongodb link

---

.travis.yml
package.json

This change attempts to reduce build flakiness by:
- updating the versions of Node and ShareDb we run Travis against
- bumping the `sharedb-mingo-memory` version to a version which [fixes its unit tests][1]
[1]: https://github.com/share/sharedb-mingo-memory/pull/5

Reduce test flakiness

---

index.js

Running `getOps` to fetch a large number of operations is not very
performant.
Anecdotally, performing this operation on a local development machine
with a document comprising of ~200,000 operations takes ~20s.
The largest slow-down appears to come from the `getLinkedOps` method,
and in particular the use of `Array.unshift`.
This change makes a very simple change that `push`es to the array
instead of `unshift`, and then `reverse`s it at the end.
The anecdotal operation time using this modified function is now ~2s,
which is an improvement of an order of magnitude.

Improve performance of `getLinkedOps`

---

index.js
package.json
test/test_mongo.js

This change updates the `MongoSnapshot` class to always include the `m`
field, in line with the [recent change to the core `Snapshot` class][1]
[1]: https://github.com/share/sharedb/pull/220/files#diff-09a9af1416a54a5b125a5c2e1e6c2a30R7

Always include `m` in snapshot

---

README.md

Previously, the numbered entries both started with 1 in the rendered README. After this change, the numbering is correct, and reads 1. then 2.

Fix Markdown numbering issue.

---

.gitignore

As a general rule-of-thumb, a `package-lock.json` is only useful in an
application (rather than a library), because:
> One key detail about `package-lock.json` is that it cannot be
> published, and it will be ignored if found in any place other than the
> toplevel package.
https://docs.npmjs.com/files/package-lock.json
This change adds `package-lock.json` to our `.gitignore`.

Ignore `package-lock.json`

---

index.js

This covers part of the work for https://github.com/share/sharedb-mongo/issues/76 - specifically, making `$aggregate` forwards-compatible with mongodb@3, if a pre-created 3.x DB client is passed into sharedb-mongo via a provider function.
`mongodb.Collection#aggregate` results in a result array in 2.x, and it results in a `mongodb.AggregationCursor` in 3.x, so check the result type and unpack it from the cursor if needed.

$aggregate forward-compatibility with mongodb@3

---

.eslintrc.js
index.js
op-link-validator.js
package.json
test/test_get_ops_without_strict_linking.js
test/test_mongo.js
test/test_op_link_validator.js
test/test_skip_poll.js

This change adds linting through `eslint`, with config read across from
[ShareDB][1]
[1]: https://github.com/share/sharedb/pull/302

Add linting

---

.travis.yml
README.md
index.js
package.json
test/test_get_ops_without_strict_linking.js
test/test_mongo.js
test/test_op_link_validator.js
test/test_skip_poll.js

* Update to MongoDB 3.x driver by default. Maintain backwards compatibility with the MongoDB 2.x driver.
* Also, update test dependencies and switch to chai for assertions

MongoDB 3.x driver

---

index.js
test/test_mongo.js

sharedb-mongo will add a `_type: {$type: 2}` to queries where the query conditions don't already filter out deleted docs.
- 2 is the [BSON type number](https://docs.mongodb.com/manual/reference/bson-types/) for string.
- `_type` contains the OT type, e.g. "http://sharejs.org/types/JSONv0", and it will be a string for non-deleted ShareDB docs and `null` for deleted ShareDB docs.
There was a bug where the `_type` condition was being unnecessarily added for queries that had both a top-level `$or` and other conditions that guarantee the query as a whole will not match deleted docs.
An artificial example - Here, the `bar: 1` guarantees that the query won't match deleted docs, but the code had still been adding `_type: {$type: 2}` to the query.
```js
{
$or: [ { foo: { $ne: true } } ],
bar: 1
} …
```

Fix unnecessary `_type: {$type: 2}` added to some $or queries

---

package.json

The only usage of async here is an `async.parallel` with 2 tasks, which isn't affected by the [breaking changes in async@2](https://github.com/caolan/async/blob/master/CHANGELOG.md#v200):
https://github.com/share/sharedb-mongo/blob/693ddd18344fe11a4adc06ef8dfeb3ad352d9726/index.js#L148-L156
We can't upgrade to async@3 because it uses ES6 features like arrow functions, and ShareDB currently targets ES5 without needing to transpile. async@2 is still actively receiving patch updates.

Upgrade to async@2

---

test/mocha.opts
test/setup.js

This change reads across the config from `sharedb` to silence the logger
in tests to reduce noise when running the test suite.

Silence logger in tests

---

index.js

In `queryPollDoc()`, the callback for `getCollectionPoll()` does not have any error handling
Thus, when `collection` is undefined and an error is returned, we hit a TypeError when we try to call `find()` on `collection`
https://github.com/share/sharedb-mongo/blob/595f092f53e2dc13c4c45f5dd89c66921e77bfbc/index.js#L865-L867

Add callback error handling in queryPollDoc

---

package.json
test/test_mongo.js

This change combines two commits that aim to greenify the build due to upstream library changes. This should also greenify the _downstream_ `sharedb` build.
This change reverts https://github.com/share/sharedb-mongo/commit/38d6f8a7130389208633007a92aa57c7a53e6e14
That change moved some tests from this library into
`sharedb-mingo-memory` and then ran them in this library by requiring
them from that one.
While this de-duplicates code, it also introduces a surprising coupling
between the tests of the two libraries. `sharedb-mingo-memory` can
add arbitrary tests to the imported suite, which may not necessarily
be applicable to `sharedb-mongo`, and even fail the `sharedb-mongo`
build, as is happening now.
This change removes that `require`, and just puts the original tests
back (ignoring any …

Greenify build

---

test/test_mongo.js

Mongo server 4.4 changed something internally that breaks the ordering of one of the `$mapReduce` tests' results. The results aren't guaranteed to be in a certain order anyways, so update the test to use an order-insensitive assertion.
Fixes https://github.com/share/sharedb-mongo/issues/95

Fix a $mapReduce test to be order insensitive

---

index.js

Fixes https://github.com/share/sharedb-mongo/issues/99 (hopefully)
It can be surprising to call `db.close()` multiple times and get an
error because we've already closed.
This change swallows the already closed error if caught in `db.close()`.
Note that a test will be added for this upstream in `sharedb`:
https://github.com/share/sharedb/pull/412

Early return `close()` if already closed

---

README.md
index.js
src/middleware/actions.js
test/test_mongo_middleware.js

This middleware is similar to the `beforeOverwrite`, but it does not have a `query` since it is a brand new document

Trigger a `beforeCreate` middleware before inserting a new document

---

.github/workflows/test.yml

**BREAKING**: Drop Node v10 support
**BREAKING**: Drop MongoDB v3.6 support
This change runs the build against Node.js v16, which was
[released in April][1]. We stop testing against v10, which has now been
end-of-lifed.
We also stop testing against MongoDB v3.6, which has also been
[end-of-lifed][2].
[1]: https://nodejs.org/en/about/releases/
[2]: https://www.mongodb.com/support-policy

👷 Update build matrix

---

index.js
test/test_mongo_middleware.js

1. Middleware was not being invoked for getting snapshot op links.
2. To do this properly, the middleware requires the upstream options configuration. This has been added to `_getOpLink`, `_getSnapshotOpLink`, and `_getSnapshotOpLinkBulk`.
No breaking API changes.
Tests passing.

Fixing Middleware Not Triggered for Getting Snapshot Op Links + Fixing Missing Options

---

index.js
mongodb.js
package.json
test/test_mongo_middleware.js

We support both `mongodb` v2 and v3 drivers, but currently only run our
tests against one version.
This change runs our test suite against both versions of the driver,
and fixes a test that breaks in v2.

✅ Run tests against both `mongodb` drivers

---

index.js
package.json

This change adds support for [`mongodb` v4][1]. The only [changes][2]
that seem to affect us are:
- removal of the top-level `connect()` function
- removal of callbacks from `MongoClient.aggregate()`
- disallowing of non-Mongo options being passed in the options object
when connecting
[1]: https://github.com/mongodb/node-mongodb-native/releases/tag/v4.0.0
[2]: https://github.com/mongodb/node-mongodb-native/blob/4.0/docs/CHANGES_4.0.0.md

⬆️ Add support for `mongodb` v4

---

README.md
index.js
package.json
test/test_mongo_middleware.js

Recently the requirement has come up for middleware to be able to modify the options passed to Mongo, specifically for queries related to op submits. This adds the ability to check for `fields.$submit` from `sharedb` and pass `options.forSubmit = true` when invoking the middleware.
We'll also need to be able to pass a set of options to the mongo driver, which the middleware can modify. This PR includes those changes.
Added tests with this use case to ensure that the Mongo driver is called with the correct options, and that when middleware changes `findOptions`, we pass those to `find`.

Pass triggeredBy = 'submitRequest' to BeforeSnapshotLookup Middleware When Lookup is For Op Submit

---

package.json

This change addresses a security warning by requiring a patched version
of `mongo@3`.

🔒 Require secure `mongo@3`

---

.github/workflows/test.yml

https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
And upgrade to latest action versions, since old ones are deprecated

GH Actions - Add manual triggering, update action versions

---

index.js
package.json
test/test_get_ops.js
test/test_get_ops_without_strict_linking.js
test/test_mongo.js
test/test_mongo_middleware.js

[`mongodb@5`][1] removes support for using callbacks, forcing consumers to use promises instead.
This non-breaking change does the minimum amount of work to move us to using `mongodb` promises, while keeping all our interfaces intact.
[1]: https://github.com/mongodb/node-mongodb-native/releases/tag/v5.0.0

♻️ Use `mongodb` promises

---

.github/workflows/test.yml

Sometimes the build can be a bit flaky, and fast fail can be quite annoying in these cases.
This change sets [`fail-fast`][1] to `false` (it defaults `true`).
[1]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

👷‍♀️ Don't fail fast

---

package.json

We incorrectly [removed `async`][1] from our dependencies, but we still import this library for our tests.
This change puts it back in our `devDependencies`
[1]: https://github.com/share/sharedb-mongo/pull/140/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L7

✅ Add `async` to `devDependencies`

---

index.js
package.json

The `mongodb@2` driver is not compatible with MongoDB v6. In order to add support for the latest database, we drop support for this old version of the `mongodb` driver.

💥 BREAKING: drop `mongodb@2` support

---

test/test_mongo.js

This is broken in a fresh install:
```
npm install
npm test
```
This is because `npm` will fetch `mongodb@5` (the latest it can), but running `npm test` without the `_SHAREDB_MONGODB_DRIVER` variable set means that the map reduce test still runs, when `mongodb@5` doesn't support it.
This change tweaks the test to check if the function is defined, instead of relying on the environment variable.

✅ Fix `npm test`

---

.github/workflows/test.yml

According to the Node.js [release schedule][1]:
- v14 will be end-of-lifed on 30 April
- v20 has been released
This change drops v14 from our test matrix, and adds v20.
[1]: https://nodejs.dev/en/about/releases/

💥 Drop Node.js 14 and add Node.js 20

---

package.json

Preemptively adding support for upcoming major versions of sharedb and sharedb-mingo-memory.
Those just drop support for Node 14, and won't have any actual breaking changes at the moment.

Add support for sharedb@4

---

package.json

This change adds support for the latest major version bump of the `mongodb` driver: [v6][1].
None of the breaks appear to affect us, so we just update our `dependencies` and test matrix.
[1]: https://github.com/mongodb/node-mongodb-native/releases/tag/v6.0.0

⬆️ Add support for `mongodb@6`

---

index.js
package.json
test/test_mongo.js

While adding tests for `$map` and `$explain` in queries in https://github.com/share/sharedb-mongo/pull/152, I found out that `$map` doesn't actually work. It just hangs since the cursor is never traversed for results.
This fixes `$map` by adding a `toArray()`. The results are delivered in the `extra` callback parameter, since the mapping function could map to something that's not a Mongo document, which would violate sharedb's assumptions around `results` being an array of Mongo docs.
I also added a test for `$explain`.

Fix $map query transform, add tests for $map and $explain

---

index.js

Starting in Mongo Node driver `mongodb@4`, up through the latest version `mongodb@6`, using `cursor.count()` results in a memory leak. `mongodb@3` doesn't leak in the same situation.
The driver creates an implicit client session, but it doesn't automatically close the session when getting the results back from the server. Those unclosed sessions build up over time, causing a memory leak.
sharedb-mongo exposes document counting via a user passing the `$count: true` property on query objects, and it currently uses `cursor.count()`.
There are a couple ways sharedb-mongo could address the leak:
- Switch to `Collection#countDocuments()`, which is the recommended replacement for the deprecated `FindCursor#count()`. This is better long-term, but it's more work since we have to map things like …

Resolve memory leak when using cursor operations like $count in mongodb@4-6

---

.github/workflows/test.yml

According to the MongoDB [release schedule][1]:
- MongoDB 4.2 is EoL this month (April 2023)
- MongoDB 7.0 was released in August
[1]: https://www.mongodb.com/legal/support-policy/lifecycles

👷‍♀️ Update MongoDB test matrix

---

index.js
test/test_mongo.js

- Fixes https://github.com/share/sharedb-mongo/issues/94
- Follows on from https://github.com/share/sharedb/pull/657
This change is to work alongside upstream work to remove ShareDB's usage of `getCommittedOpVersion()`.
In `sharedb-mongo` this function requires an entire extra op index, just to handle a corner case where two `create` ops are submitted at the same time, which should happen relatively infrequently.
This change allows consumers to opt out of individual indexes. For example, if we're not using `getCommittedOpVersion()`, consumers can opt out of the automatic `src`/`seq`/`v` index creation with:
```js
new ShareDbMongo(
mongoUrl,
{
disableIndexCreation: {
src_seq_v: true,
},
},
);
```
Note that if this index already exists, consumers will need to manually remove it.
Previous …

🔧 Allow disabling the `src`/`seq`/`v` index

---

test/test_mongo.js

Sometimes this test fails with:
```
1) mongo db connection
via url string with mongoPoll and pollDelay option
delays queryPoll but not commit:
Uncaught AssertionError: expected 1000 to be above 1000
+ expected - actual
at /home/runner/work/sharedb-mongo/sharedb-mongo/test/test_mongo.js:541:48
at /home/runner/work/sharedb-mongo/sharedb-mongo/index.js:133:2086
at /home/runner/work/sharedb-mongo/sharedb-mongo/index.js:133:109
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
We don't care about the exact millisecond, so this change updates the assertion to `greaterThanOrEqual()`

✅ Fix a slightly flaky test
